import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme {
  static final theme = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff065808),
      primaryContainer: Color(0xff9ee29f),
      secondary: Color(0xff365b37),
      secondaryContainer: Color(0xffaebdaf),
      tertiary: Color(0xff2c7e2e),
      tertiaryContainer: Color(0xffb8e6b9),
      appBarColor: Color(0xffb8e6b9),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 22,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 1.0,
    lightIsWhite: true,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 10,
      blendOnColors: false,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSparkle,
      textButtonRadius: 6.0,
      filledButtonRadius: 6.0,
      elevatedButtonRadius: 6.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 6.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 1.0,
      toggleButtonsRadius: 6.0,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 6.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderWidth: 0.5,
      switchThumbFixedSize: true,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 2,
      inputDecoratorRadius: 6.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      fabRadius: 6.0,
      fabSchemeColor: SchemeColor.tertiary,
      chipRadius: 6.0,
      cardRadius: 6.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipWaitDuration: Duration(milliseconds: 300),
      tooltipShowDuration: Duration(milliseconds: 500),
      dialogElevation: 3.0,
      dialogRadius: 6.0,
      snackBarRadius: 6,
      tabBarIndicatorWeight: 1.5,
      tabBarDividerColor: Color(0x00000000),
      drawerRadius: 6.0,
      drawerIndicatorRadius: 6.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetRadius: 6.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
      bottomNavigationBarShowUnselectedLabels: false,
      menuRadius: 6.0,
      menuElevation: 4.0,
      menuBarRadius: 6.0,
      menuBarElevation: 1.0,
      menuIndicatorRadius: 6.0,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 0.60,
      navigationBarIndicatorRadius: 6.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 0.60,
      navigationRailIndicatorRadius: 6.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.none,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepPrimary: true,
      keepSecondary: true,
      keepTertiary: true,
    ),
    tones: FlexTones.ultraContrast(Brightness.light)
        .onMainsUseBW()
        .onSurfacesUseBW(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
  );

  static final darkTheme = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xff629f80),
      primaryContainer: Color(0xff274033),
      secondary: Color(0xff81b39a),
      secondaryContainer: Color(0xff4d6b5c),
      tertiary: Color(0xff88c5a6),
      tertiaryContainer: Color(0xff356c50),
      appBarColor: Color(0xff356c50),
      error: Color(0xffcf6679),
    ),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 15,
    appBarStyle: FlexAppBarStyle.scaffoldBackground,
    darkIsTrueBlack: true,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      blendTextTheme: true,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSparkle,
      textButtonRadius: 6.0,
      filledButtonRadius: 6.0,
      elevatedButtonRadius: 6.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 6.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 1.0,
      toggleButtonsRadius: 6.0,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 6.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderWidth: 0.5,
      switchThumbFixedSize: true,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 2,
      inputDecoratorRadius: 6.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      fabRadius: 6.0,
      fabSchemeColor: SchemeColor.tertiary,
      chipRadius: 6.0,
      cardRadius: 6.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipWaitDuration: Duration(milliseconds: 300),
      tooltipShowDuration: Duration(milliseconds: 500),
      dialogElevation: 3.0,
      dialogRadius: 6.0,
      snackBarRadius: 6,
      tabBarIndicatorWeight: 1.5,
      tabBarDividerColor: Color(0x00000000),
      drawerRadius: 6.0,
      drawerIndicatorRadius: 6.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetRadius: 6.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
      bottomNavigationBarShowUnselectedLabels: false,
      menuRadius: 6.0,
      menuElevation: 4.0,
      menuBarRadius: 6.0,
      menuBarElevation: 1.0,
      menuIndicatorRadius: 6.0,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 0.60,
      navigationBarIndicatorRadius: 6.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 0.60,
      navigationRailIndicatorRadius: 6.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.none,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
    ),
    tones: FlexTones.ultraContrast(Brightness.dark),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: GoogleFonts.sourceCodePro().fontFamily,
    typography: Typography.material2021(),
    textTheme: GoogleFonts.sourceCodeProTextTheme(),
  );
}
