name: project_me
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # ui

  # firebase
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  # management
  flutter_hooks: ^0.20.3
  go_router: ^12.0.0
  hooks_riverpod: ^2.4.4
  # util
  intl: ^0.18.1
  nanoid2: ^2.0.1
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  shimmer_animation: ^2.1.0+1
  cached_network_image: ^3.3.0
  fpdart: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.1

flutter:
  uses-material-design: true
