// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZRX9__WyPRQA3yH-jfd516di0KCd5NA',
    appId: '1:469679123074:web:8b8c6f6b9075884022229b',
    messagingSenderId: '469679123074',
    projectId: 'ahnaf-sakil',
    authDomain: 'ahnaf-sakil.firebaseapp.com',
    storageBucket: 'ahnaf-sakil.appspot.com',
    measurementId: 'G-BSR7YJGT7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47JeLG2p_CTx8r6UWSWiZMQ2Z2Lvdxrg',
    appId: '1:469679123074:android:c3c6b5ec7f65113c22229b',
    messagingSenderId: '469679123074',
    projectId: 'ahnaf-sakil',
    storageBucket: 'ahnaf-sakil.appspot.com',
  );
}
